"""empty message

Revision ID: 4c903bc0185d
Revises: c91d6aa2b78
Create Date: 2014-12-22 15:42:08.801264

"""

# revision identifiers, used by Alembic.
revision = '4c903bc0185d'
down_revision = 'c91d6aa2b78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slug', sa.String(length=64), nullable=True))
    op.drop_column('project', 'pretty_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pretty_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('project', 'slug')
    ### end Alembic commands ###
