"""empty message

Revision ID: ad9ab1cee4
Revises: 19e28e1e2ce8
Create Date: 2015-01-08 14:39:48.842378

"""

# revision identifiers, used by Alembic.
revision = 'ad9ab1cee4'
down_revision = '19e28e1e2ce8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'project_id')
    op.add_column('plot', sa.Column('crawl_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'plot', 'crawl', ['crawl_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plot', type_='foreignkey')
    op.drop_column('plot', 'crawl_id')
    op.add_column('image', sa.Column('project_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'image', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###
