"""empty message

Revision ID: c91d6aa2b78
Revises: 1f0328fe4fd5
Create Date: 2014-12-22 12:15:16.376413

"""

# revision identifiers, used by Alembic.
revision = 'c91d6aa2b78'
down_revision = '1f0328fe4fd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pretty_name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'pretty_name')
    ### end Alembic commands ###
